--Magnitude analysis
--========================
SELECT *
FROM gold.dim_customers
--find total customers by country
SELECT
	country,
	COUNT (customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;
--find total customers by gender
SELECT 
	gender,
	COUNT(customer_id) total_customers_by_gender 
FROM gold.dim_customers
GROUP BY gender;

--find total roducts by category
SELECT 
	category,
	COUNT (product_key) AS total_product_category
FROM gold.dim_products
GROUP BY category
ORDER BY total_product_category DESC;
-- what is the average cost in each category 
SELECT 
	category,
	AVG (product_cost) AS avg_cost_category
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost_category DESC;

--Which categories have the highest product cost base”
SELECT 
	category,
	SUM (product_cost) AS total_cost_category
FROM gold.dim_products
GROUP BY category
ORDER BY total_cost_category DESC;

-- total revenue generated by each category 
SELECT 
	p.category,
	SUM(s.sales_amount) AS total_category_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_category_revenue DESC;
-- total revenue generated by each customer
SELECT 
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) as total_customer_revenue
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY 
	c.customer_id,
	c.first_name,
	c.last_name
ORDER BY total_customer_revenue DESC;

-- distribution of sold items across countries 
SELECT 
	c.country,
	SUM(s.sales_quantity) AS total_sold_items
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
